# frozen_string_literal: true

source "https://rubygems.org"

gemspec path: '../himari'
# Specify your gem's dependencies in himari-aws.gemspec
gemspec

gem 'nokogiri'

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
