name: main

on:
  push:
    branches:
      - main
      - test

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/_test.yml

  himari-lambda-image:
    needs: [test]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image-tag: "public.ecr.aws/sorah/himari-lambda:${{ github.sha }}"
    steps:
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          aws-region: "us-west-2"
          role-skip-session-tagging: true
          role-to-assume: "arn:aws:iam::341857463381:role/gha-himari"
          mask-aws-account-id: 'false' # only string works
      - id: login-ecr
        name: 'Login to ECR Public'
        run: 'aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws'
      - run: "echo '${{ github.sha }}' > REVISION"
      - name: 'Build image'
        uses: 'docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f' # v7.1.0
        with:
          context: '.'
          file: './himari-aws/lambda/Dockerfile'
          push: true
          tags: "public.ecr.aws/sorah/himari-lambda:${{ github.sha }},public.ecr.aws/sorah/himari-lambda:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max


