name: main

on:
  push:
    branches:
      - main
      - test

permissions: {}

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/_test.yml

  himari-lambda-image:
    needs: [test]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image-tag: "public.ecr.aws/sorah/himari-lambda:${{ github.sha }}"
    steps:
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: aws-actions/configure-aws-credentials@acca2b1b2070338fb9fd1ca27ecee81d687e58e5 # v6.1.2
        with:
          aws-region: "us-west-2"
          role-skip-session-tagging: true
          role-to-assume: "arn:aws:iam::341857463381:role/gha-himari"
          mask-aws-account-id: 'false' # only string works
      - id: login-ecr
        name: 'Login to ECR Public'
        run: 'aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws'
      - run: "echo '${{ github.sha }}' > REVISION"
      - name: 'Build image'
        uses: 'docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf' # v7.2.0
        with:
          context: '.'
          file: './himari-aws/lambda/Dockerfile'
          push: true
          tags: "public.ecr.aws/sorah/himari-lambda:${{ github.sha }},public.ecr.aws/sorah/himari-lambda:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max


